//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ISPTool.rc
//
#define IDM_ABOUTBOX                                 0x0010
#define IDD_ABOUTBOX                                 100
#define IDD_DIALOG_CONFIGURATION_NUC100              101
#define IDD_DIALOG_HEX                               102
#define IDD_DIALOG_CONFIGURATION_M051                103
#define IDD_DIALOG_NUVOISP                           104
#define IDD_DIALOG_NUVOISP_WITH_SPI                  105
#define IDD_DIALOG_CONFIGURATION_NANO100             106
#define IDD_DIALOG_CONFIGURATION_MINI51              107
#define IDD_DIALOG_CONFIGURATION_NUC200              108
#define IDD_DIALOG_CONFIGURATION_NUC103              109
#define IDD_DIALOG_CONFIGURATION_M051CN              110
#define IDD_DIALOG_CONFIGURATION_MT500               111
#define IDD_DIALOG_CONFIGURATION_N572                112
#define IDD_DIALOG_CONFIGURATION_AU9100              113
#define IDD_DIALOG_CONFIGURATION_M058                114
#define IDD_DIALOG_CONFIGURATION_NUC400              115
#define IDD_DIALOG_CONFIGURATION_MINI51CN            116
#define IDD_DIALOG_CONFIGURATION_NUC103BN            117
#define IDD_DIALOG_CONFIGURATION_NANO112             118
#define IDD_DIALOG_CONFIGURATION_NM1200              119
#define IDD_DIALOG_CONFIGURATION_NANO103             120
#define IDD_DIALOG_CONFIGURATION_NM1120              121
#define IDD_DIALOG_CONFIGURATION_N570                122
#define IDD_DIALOG_CONFIGURATION_OT8051              123
#define IDD_DIALOG_CONFIGURATION_M0564               124
#define IDD_DIALOG_CHIP_SETTING_M2351                125
#define IDD_DIALOG_CHIP_SETTING_CFG_M2351            126
#define IDD_DIALOG_CONFIGURATION_I94000              127
#define IDD_DIALOG_CHIP_SETTING_M251                 128
#define IDD_DIALOG_CHIP_SETTING_CFG_M251             129
#define IDD_DIALOG_CONFIGURATION_M480LD              130
#define IDD_DIALOG_CONFIGURATION_M480                131
#define IDD_DIALOG_CONFIGURATION_I91200              132
#define IDD_DIALOG_CHIP_SETTING_CFG_M258             133
#define IDD_DIALOG_CHIP_SETTING_NUMICRO1             134
#define IDD_DIALOG_CHIP_SETTING_NUMICRO              135
#define IDD_DIALOG_CHIP_SETTING_CFG_M0A21            136
#define IDD_DIALOG_CONFIGURATION_NUC102              137
#define IDD_DIALOG_CONFIGURATION_NUC1262             138
#define IDD_DIALOG_CHIP_SETTING_CFG_M460             139
#define IDD_DIALOG_CHIP_SETTING_CFG_M2L31            140
#define IDD_DIALOG_CHIP_SETTING_CFG_M55M1            141
#define IDD_DIALOG_CHIP_SETTING_CFG_M2A23            142
#define IDD_DIALOG_OFFLINE_LUA                       143
#define IDD_DIALOG_CONFIGURATION_M451                144
#define IDD_DIALOG_CHIP_SETTING_SECURE_M2351         145
#define IDD_DIALOG_CONFIGURATION_M031                146
#define IDD_DIALOG_CONFIGURATION_N572F064            147
#define IDD_DIALOG_CONFIGURATION_N572F072            148
#define IDD_DIALOG_CHIP_SETTING_NSCBA                149
#define IDD_DIALOG_CONFIGURATION_I96000              150
#define IDD_DIALOG_CONFIGURATION_N574                151
#define IDD_DIALOG_CHIP_SETTING_NUMICRO2             152
#define IDD_DIALOG_CHIP_SETTING_APWPROT              153
#define IDD_DIALOG_CONFIGURATION_N79E855             154
#define IDD_DIALOG_CHIP_SETTING_NSCBA_LOCK           155
#define IDD_DIALOG_CHIP_SETTING_CFG_M2U51            156
#define IDD_DIALOG_CHIP_SETTING_CFG_M3331            157
#define IDD_DIALOG_CHIP_SETTING_LDWPROT              158
#define IDR_MAINFRAME                                1000
#define IDB_BITMAP_BANNER                            1001
#define IDB_BITMAP_NUVOTON                           1002
#define IDI_ICON_MEMORY                              1003
#define IDB_BITMAP_CHIPS                             1004
#define IDC_GROUP_INTERFACE                          1005
#define IDC_COMBO_INTERFACE                          1006
#define IDC_COMBO_COM_PORT                           1007
#define IDC_CHECK_RUN_APROM                          1008
#define IDC_LINK_GITHUB                              1009
#define IDC_LINK_GITEE                               1010
#define IDC_LINK_GITLAB                              1011
#define IDI_ICON_NULINK                              1012
#define IDI_ICON_KEY_INPUT                           1013
#define IDC_PROGRESS                                 1014
#define IDC_BUTTON_CONNECT                           1015
#define IDC_BUTTON_CONFIG                            1016
#define IDC_BUTTON_START                             1017
#define IDC_BUTTON_APROM                             1018
#define IDC_BUTTON_NVM                               1019
#define IDC_CHECK_LDROM                              1020
#define IDC_CHECK_APROM                              1021
#define IDC_CHECK_NVM                                1022
#define IDC_CHECK_CONFIG                             1023
#define IDC_GROUP_CONNECT                            1024
#define IDC_STATIC_CONNECT                           1025
#define IDC_STATIC_PARTNO                            1026
#define IDC_GROUP_FLASH_FILE                         1027
#define IDC_STATIC_FILENAME_0                        1028
#define IDC_STATIC_FILENAME_1                        1029
#define IDC_STATIC_FILEINFO_APROM                    1030
#define IDC_STATIC_FILENAME_2                        1031
#define IDC_STATIC_FILEINFO_NVM                      1032
#define IDC_STATIC_FILENAME_3                        1033
#define IDC_GROUP_DATA                               1034
#define IDC_STATIC_FILENAME_4                        1035
#define IDC_GROUP_FILE_DATA                          1036
#define IDC_GROUP_PROGRAM                            1037
#define IDC_STATIC_STATUS                            1038
#define IDC_EDIT_FILEPATH_APROM                      1039
#define IDC_EDIT_FILEPATH_NVM                        1040
#define IDC_TAB_DATA                                 1041
#define IDC_CHECK_ERASE                              1042
#define IDC_CHECK_ERASE_SPI                          1043
#define IDC_EDIT_PARTNO                              1044
#define IDC_BUTTON_SAVE_AS                           1045
#define IDC_RADIO_UINT8                              1046
#define IDC_RADIO_UINT16                             1047
#define IDC_RADIO_UINT32                             1048
#define IDC_RICHEDIT_DATAVIEW                        1049
#define IDC_EDIT_DATAVIEW                            1050
#define IDC_LINK_NUVOTON                             1051
#define IDC_STATIC_MESSAGE                           1052
#define IDC_EDIT_APROM_BASE_ADDRESS                  1053
#define IDC_STATIC_APOFFSET                          1054
#define IDC_RADIO_HIRC_ENABLE                        1055
#define IDC_RADIO_HIRC                               1056
#define IDC_CHECK_LVOL_RSTEN                         1057
#define IDC_CHECK_BOD_HYS_EN                         1058
#define IDC_BUTTON_SPI                               1059
#define IDC_EDIT_FILEPATH_SPI                        1060
#define IDC_STATIC_FILEINFO_SPI                      1061
#define IDC_CHECK_SPI                                1062
#define IDC_BUTTON_DEFAULT                           1063
#define IDC_CHECK_ADCINTEN                           1064
#define IDC_STATIC_FILENAME_SPI                      1065
#define IDC_EDIT_IPADDRESS                           1066
#define IDC_EDIT_IPPORT                              1067
#define IDC_CHECK_SECURITY_BOOT_LOCK                 1068
#define IDC_EDIT_FLASH_INFO2                         1069
#define IDC_EDIT_FLASH_INFO3                         1070
#define IDC_EDIT_FLASH_INFO4                         1071
#define IDC_GROUP_IODEFAULT                          1072
#define IDC_GROUP_SYSCLKDIV                          1073
#define IDC_GROUP_ISP_MODE                           1074
#define IDC_RADIO_IODEFAULT_INPUT                    1075
#define IDC_RADIO_IODEFAULT_QUASI                    1076
#define IDC_RADIO_SYSCLKDIV_0                        1077
#define IDC_RADIO_SYSCLKDIV_1                        1078
#define IDC_RADIO_SYSCLKDIV_2                        1079
#define IDC_RADIO_SYSCLKDIV_3                        1080
#define IDC_CHECK_ISP_MODE_UART                      1081
#define IDC_CHECK_ISP_MODE_USB                       1082
#define IDC_CHECK_ISP_MODE_CAN                       1083
#define IDC_CHECK_ISP_MODE_I2C                       1084
#define IDC_CHECK_ISP_MODE_SPI                       1085
#define IDC_STATIC_FLASH_KEYSTORE_LOCK               1086
#define IDC_EDIT_FLASH_KEYSTORE_LOCK                 1087
#define IDC_EDIT_BDNAME                              1088
#define IDC_EDIT_FILENAME                            1089
#define IDC_RADIO1                                   1090
#define IDC_RADIO2                                   1091
#define IDC_RADIO3                                   1092
#define IDC_CHECK_LIMIT                              1093
#define IDC_EDIT_LIMIT                               1094
#define IDC_GROUP_CVDTV                              1095
#define IDC_RADIO_CVDTV_27                           1096
#define IDC_RADIO_CVDTV_30                           1097
#define IDC_CHECK_CVDEN                              1098
#define IDC_EDIT_FLASH_INFO1                         1099
#define IDC_CHECK_CWDTEN_072                         1100
#define IDC_CHECK_CVDEN_072                          1101
#define IDC_CHECK_PROTECTION_8K_072                  1102
#define IDC_CHECK_LOCK_072                           1103
#define IDC_COMBO_CSPI0_CT_072                       1104
#define IDC_COMBO_CSPI0_FT_072                       1105
#define IDC_RADIO_CVDTV_27_072                       1106
#define IDC_GROUP_CSPI0_072                          1107
#define IDC_GROUP_CVDTV_072                          1108
#define IDC_RADIO_CVDTV_30_072                       1109
#define IDC_STATIC_CONFIG_0_072                      1110
#define IDC_STATIC_CONFIG_VALUE_0_072                1111
#define IDC_GROUP_CONFIG_VALUE_072                   1112
#define IDC_TAB_CHIP_SETTING                         1113
#define IDC_CANCEL                                   1114
#define IDC_STATIC_CONFIG_0                          1115
#define IDC_STATIC_CONFIG_VALUE_0                    1116
#define IDC_STATIC_CONFIG_1                          1117
#define IDC_STATIC_CONFIG_VALUE_1                    1118
#define IDC_STATIC_CONFIG_2                          1119
#define IDC_STATIC_CONFIG_VALUE_2                    1120
#define IDC_STATIC_CONFIG_3                          1121
#define IDC_STATIC_CONFIG_VALUE_3                    1122
#define IDC_STATIC_CONFIG_4                          1123
#define IDC_STATIC_CONFIG_VALUE_4                    1124
#define IDC_STATIC_CONFIG_5                          1125
#define IDC_STATIC_CONFIG_VALUE_5                    1126
#define IDC_STATIC_CONFIG_6                          1127
#define IDC_STATIC_CONFIG_VALUE_6                    1128
#define IDC_STATIC_CONFIG_8                          1129
#define IDC_STATIC_CONFIG_VALUE_8                    1130
#define IDC_STATIC_CONFIG_9                          1131
#define IDC_STATIC_CONFIG_VALUE_9                    1132
#define IDC_STATIC_CONFIG_10                         1133
#define IDC_STATIC_CONFIG_VALUE_10                   1134
#define IDC_STATIC_CONFIG_11                         1135
#define IDC_STATIC_CONFIG_VALUE_11                   1136
#define IDC_STATIC_CONFIG_12                         1137
#define IDC_STATIC_CONFIG_VALUE_12                   1138
#define IDC_STATIC_CONFIG_13                         1139
#define IDC_STATIC_CONFIG_VALUE_13                   1140
#define IDC_STATIC_CONFIG_14                         1141
#define IDC_STATIC_CONFIG_VALUE_14                   1142
#define IDC_STATIC_CONFIG_16                         1143
#define IDC_STATIC_CONFIG_VALUE_16                   1144
#define IDC_STATIC_CONFIG_17                         1145
#define IDC_STATIC_CONFIG_VALUE_17                   1146
#define IDC_STATIC_CONFIG_18                         1147
#define IDC_STATIC_CONFIG_VALUE_18                   1148
#define IDC_GROUP_SECURE_CONCEAL                     1149
#define IDC_STATIC_SECURE_CONCEAL_BASE_ADDR          1150
#define IDC_STATIC_SECURE_CONCEAL_PAGE_COUNT         1151
#define IDC_CHECK_SECURE_CONCEAL                     1152
#define IDC_EDIT_SECURE_CONCEAL_BASE_ADDR            1153
#define IDC_EDIT_SECURE_CONCEAL_PAGE_COUNT           1154
#define IDC_GROUP_APROM_WPROT                        1155
#define IDC_GROUP_APROM_WPROT_LEVEL                  1156
#define IDC_RADIO_APROM_WPROT_LEVEL0                 1157
#define IDC_RADIO_APROM_WPROT_LEVEL1                 1158
#define IDC_RADIO_APROM_WPROT_LEVEL2                 1159
#define IDC_RADIO_APROM_WPROT_LEVEL3                 1160
#define IDC_GROUP_APROM_WPROT_PIN                    1161
#define IDC_RADIO_APROM_WPROT_PIN_A                  1162
#define IDC_RADIO_APROM_WPROT_PIN_B                  1163
#define IDC_RADIO_APROM_WPROT_PIN_C                  1164
#define IDC_RADIO_APROM_WPROT_PIN_D                  1165
#define IDC_GROUP_BLISP_UART_SEL                     1166
#define IDC_RADIO_BLISP_UART_SEL_0                   1167
#define IDC_RADIO_BLISP_UART_SEL_1                   1168
#define IDC_RADIO_BLISP_UART_SEL_2                   1169
#define IDC_RADIO_BLISP_UART_SEL_3                   1170
#define IDC_CHECK_APROM_WPROT_0                      1171
#define IDC_CHECK_APROM_WPROT_1                      1172
#define IDC_CHECK_APROM_WPROT_2                      1173
#define IDC_CHECK_APROM_WPROT_3                      1174
#define IDC_CHECK_APROM_WPROT_4                      1175
#define IDC_CHECK_APROM_WPROT_5                      1176
#define IDC_CHECK_APROM_WPROT_6                      1177
#define IDC_CHECK_APROM_WPROT_7                      1178
#define IDC_CHECK_APROM_WPROT_8                      1179
#define IDC_CHECK_APROM_WPROT_9                      1180
#define IDC_CHECK_APROM_WPROT_10                     1181
#define IDC_CHECK_APROM_WPROT_11                     1182
#define IDC_CHECK_APROM_WPROT_12                     1183
#define IDC_CHECK_APROM_WPROT_13                     1184
#define IDC_CHECK_APROM_WPROT_14                     1185
#define IDC_CHECK_APROM_WPROT_15                     1186
#define IDC_CHECK_APROM_WPROT_16                     1187
#define IDC_CHECK_APROM_WPROT_17                     1188
#define IDC_CHECK_APROM_WPROT_18                     1189
#define IDC_CHECK_APROM_WPROT_19                     1190
#define IDC_CHECK_APROM_WPROT_20                     1191
#define IDC_CHECK_APROM_WPROT_21                     1192
#define IDC_CHECK_APROM_WPROT_22                     1193
#define IDC_CHECK_APROM_WPROT_23                     1194
#define IDC_CHECK_APROM_WPROT_24                     1195
#define IDC_CHECK_APROM_WPROT_25                     1196
#define IDC_CHECK_APROM_WPROT_26                     1197
#define IDC_CHECK_APROM_WPROT_27                     1198
#define IDC_CHECK_APROM_WPROT_28                     1199
#define IDC_CHECK_APROM_WPROT_29                     1200
#define IDC_CHECK_APROM_WPROT_30                     1201
#define IDC_CHECK_APROM_WPROT_31                     1202
#define IDC_CHECK_APROM_WPROT_32                     1203
#define IDC_CHECK_APROM_WPROT_33                     1204
#define IDC_CHECK_APROM_WPROT_34                     1205
#define IDC_CHECK_APROM_WPROT_35                     1206
#define IDC_CHECK_APROM_WPROT_36                     1207
#define IDC_CHECK_APROM_WPROT_37                     1208
#define IDC_CHECK_APROM_WPROT_38                     1209
#define IDC_CHECK_APROM_WPROT_39                     1210
#define IDC_CHECK_APROM_WPROT_40                     1211
#define IDC_CHECK_APROM_WPROT_41                     1212
#define IDC_CHECK_APROM_WPROT_42                     1213
#define IDC_CHECK_APROM_WPROT_43                     1214
#define IDC_CHECK_APROM_WPROT_44                     1215
#define IDC_CHECK_APROM_WPROT_45                     1216
#define IDC_CHECK_APROM_WPROT_46                     1217
#define IDC_CHECK_APROM_WPROT_47                     1218
#define IDC_CHECK_APROM_WPROT_48                     1219
#define IDC_CHECK_APROM_WPROT_49                     1220
#define IDC_CHECK_APROM_WPROT_50                     1221
#define IDC_CHECK_APROM_WPROT_51                     1222
#define IDC_CHECK_APROM_WPROT_52                     1223
#define IDC_CHECK_APROM_WPROT_53                     1224
#define IDC_CHECK_APROM_WPROT_54                     1225
#define IDC_CHECK_APROM_WPROT_55                     1226
#define IDC_CHECK_APROM_WPROT_56                     1227
#define IDC_CHECK_APROM_WPROT_57                     1228
#define IDC_CHECK_APROM_WPROT_58                     1229
#define IDC_CHECK_APROM_WPROT_59                     1230
#define IDC_CHECK_APROM_WPROT_60                     1231
#define IDC_CHECK_APROM_WPROT_61                     1232
#define IDC_CHECK_APROM_WPROT_62                     1233
#define IDC_CHECK_APROM_WPROT_63                     1234
#define IDC_STATIC_APROM_WPROT0                      1235
#define IDC_BUTTON_APROM_WPROT0_SELECT_ALL           1236
#define IDC_BUTTON_APROM_WPROT0_CLEAR_ALL            1237
#define IDC_STATIC_APROM_WPROT1                      1238
#define IDC_BUTTON_APROM_WPROT1_SELECT_ALL           1239
#define IDC_BUTTON_APROM_WPROT1_CLEAR_ALL            1240
#define IDC_GROUP_BL_SPEED_SEL                       1241
#define IDC_RADIO_BL_SPEED_SEL_0                     1242
#define IDC_RADIO_BL_SPEED_SEL_1                     1243
#define IDC_GROUP_OSCFS                              1244
#define IDC_RADIO_OSCFS_22M                          1245
#define IDC_RADIO_OSCFS_11M                          1246
#define IDC_RADIO_FOSC_HIRC                          1247
#define IDC_RADIO_FOSC_XTAL_PIN                      1248
#define IDC_RADIO_FOSC_HXT                           1249
#define IDC_GROUP_CWDTCSEL                           1250
#define IDC_RADIO_CWDTCSEL_NORMAL                    1251
#define IDC_RADIO_CWDTCSEL_HIGH_ACCURACY             1252
#define ID_MENUITEM_EXPORT                           1253
#define IDC_GROUP_LDROM_WPROT                        1254
#define IDC_CHECK_LDROM_WPROT_0                      1255
#define IDC_CHECK_LDROM_WPROT_1                      1256
#define IDC_GROUP_LDROM_WPROT_LEVEL                  1257
#define IDC_RADIO_LDROM_WPROT_LEVEL0                 1258
#define IDC_RADIO_LDROM_WPROT_LEVEL1                 1259
#define IDC_GROUP_DFLASH_WPROT                       1260
#define IDC_CHECK_DFLASH_WPROT_0                     1261
#define IDC_CHECK_DFLASH_WPROT_1                     1262
#define IDC_CHECK_DFLASH_WPROT_2                     1263
#define IDC_CHECK_DFLASH_WPROT_3                     1264
#define IDC_CHECK_SRAM_ECC                           1265
#define IDS_SIZE_M_BYTES                             1266
#define IDS_SIZE_K_BYTES                             1267
#define IDS_SIZE_BYTES                               1268
#define IDS_PS_CHECKSUM_PX                           1269
#define IDS_PS_CHECKSUM_CRC8_PX                      1270
#define IDS_ENABLE_SECURITY_LOCK                     1271
#define IDS_SELECT_EXTERNAL_12M_CLOCK                1272
#define IDS_SELECT_EXTERNAL_32K_CLOCK                1273
#define IDS_SELECT_PLL_CLOCK                         1274
#define IDS_DISABLE_SECURITY_LOCK                    1275
#define IDS_M0A21_SERIES                             1276
#define IDS_M031_SERIES                              1277
#define IDS_M451_SERIES                              1278
#define IDS_M471_SERIES                              1279
#define IDS_M030G_SERIES                             1280
#define IDS_M2351_SERIES                             1281
#define IDS_M55M1_SERIES                             1282
#define IDS_PS_CHECKSUM_CRC32_PX                     1283
#define IDS_RPD_P12                                  1284
#define IDS_RPD_P20                                  1285
#define IDS_RPD_P36                                  1286
#define IDS_RPD_P12_RESET                            1287
#define IDS_RPD_P12_INPUT                            1288
#define IDS_RPD_P36_RESET                            1289
#define IDS_RPD_P36_INPUT                            1290
#define IDS_RPD_P20_RESET                            1291
#define IDS_RPD_P20_INPUT                            1292
#define IDS_CM2003_SERIES                            1293
#define IDS_WPROT_REGION                             1294
#define IDS_M091_SERIES                              1295
#define IDS_M2003_SERIES                             1296
#define IDS_OTFC_PR                                  1297
#define IDC_GROUP_CLOCK_SOURCE                       1298
#define IDC_GROUP_BOOT_SELECT                        1299
#define IDC_GROUP_BROWN_OUT_VOLTAGE                  1300
#define IDC_GROUP_BROWN_OUT_RESET_VOLTAGE            1301
#define IDC_GROUP_GPF                                1302
#define IDC_GROUP_GPF2                               1303
#define IDC_GROUP_PA8_STATE                          1304
#define IDC_GROUP_IO_STATE                           1305
#define IDC_GROUP_CONFIG_VALUE                       1306
#define IDC_GROUP_CONFIG                             1307
#define IDC_GROUP_DATA_FLASH                         1308
#define IDC_GROUP_RC_TRIM4                           1309
#define IDC_GROUP_MII_MODE                           1310
#define IDC_GROUP_SPIM_SELECT                        1311
#define IDC_GROUP_UART1_SELECT                       1312
#define IDC_GROUP_LVR_LEVEL                          1313
#define IDC_GROUP_HXT_MODE                           1314
#define IDC_GROUP_CHIPRESET_TIMEEXT                  1315
#define IDC_GROUP_RST_PIN_WIDTH                      1316
#define IDC_GROUP_NSCBA                              1317
#define IDC_GROUP_TWO_LEVEL_LOCK                     1318
#define IDC_GROUP_ADVANCE_LOCK                       1319
#define IDC_RADIO_CLK_E12M6M                         1320
#define IDC_RADIO_CLK_E12M                           1321
#define IDC_RADIO_CLK_I24M                           1322
#define IDC_RADIO_CLK_I22M                           1323
#define IDC_CHECK_CLOCK_FILTER_ENABLE                1324
#define IDC_CHECK_BS_MKROM                           1325
#define IDC_CHECK_BOOT_LOADER                        1326
#define IDC_RADIO_BS_LDROM                           1327
#define IDC_RADIO_BS_APROM                           1328
#define IDC_RADIO_BS_APROM_LDROM                     1329
#define IDC_RADIO_BS_LDROM_APROM                     1330
#define IDC_RADIO_BOV_DISABLE                        1331
#define IDC_RADIO_BOV_0                              1332
#define IDC_RADIO_BOV_1                              1333
#define IDC_RADIO_BOV_2                              1334
#define IDC_RADIO_BOV_3                              1335
#define IDC_RADIO_BOV_4                              1336
#define IDC_RADIO_BOV_5                              1337
#define IDC_RADIO_BOV_6                              1338
#define IDC_RADIO_BOV_7                              1339
#define IDC_RADIO_BOV_8                              1340
#define IDC_RADIO_BOV_9                              1341
#define IDC_RADIO_BOV_A                              1342
#define IDC_RADIO_BOV_B                              1343
#define IDC_RADIO_BOV_C                              1344
#define IDC_RADIO_BOV_D                              1345
#define IDC_RADIO_BOV_E                              1346
#define IDC_RADIO_BOV_F                              1347
#define IDC_CHECK_BROWN_OUT_DETECT                   1348
#define IDC_CHECK_BROWN_OUT_RESET                    1349
#define IDC_CHECK_BROWN_OUT_ENABLE                   1350
#define IDC_CHECK_BROWN_OUT_IAP                      1351
#define IDC_RADIO_GPF_GPIO                           1352
#define IDC_RADIO_GPF_CRYSTAL                        1353
#define IDC_RADIO_GPG2_GPIO                          1354
#define IDC_RADIO_GPG2_32K                           1355
#define IDC_RADIO_PA8_IOINI                          1356
#define IDC_RADIO_PA8_LOW                            1357
#define IDC_RADIO_IO_TRI                             1358
#define IDC_RADIO_IO_BI                              1359
#define IDC_RADIO_IO_PO                              1360
#define IDC_CHECK_DATA_FLASH_ENABLE                  1361
#define IDC_STATIC_FLASH_BASE_ADDRESS                1362
#define IDC_EDIT_FLASH_BASE_ADDRESS                  1363
#define IDC_EDIT_DATA_FLASH_SIZE                     1364
#define IDC_SPIN_DATA_FLASH_SIZE                     1365
#define IDC_STATIC_DATA_FLASH_SIZE                   1366
#define IDC_CHECK_DATA_FLASH_VAR_SIZE_ENABLE         1367
#define IDC_STATIC_FLASH_ADVANCE_LOCK                1368
#define IDC_EDIT_FLASH_ADVANCE_LOCK                  1369
#define IDC_CHECK_SECURITY_LOCK                      1370
#define IDC_CHECK_ICE_LOCK                           1371
#define IDC_CHECK_WDT_ENABLE                         1372
#define IDC_CHECK_WDT_POWER_DOWN                     1373
#define IDC_SPROM_LOCK_CACHEABLE                     1374
#define IDC_CHECK_SECURITYBOOT_LOCK                  1375
#define IDC_CHECK_CLOCK_STOP_DETECT                  1376
#define IDC_CHECK_MASS_ERASE                         1377
#define IDC_CHECK_LDROM_EN                           1378
#define IDC_RADIO_RC_44M                             1379
#define IDC_RADIO_RC_48M                             1380
#define IDC_RADIO_RC_22M                             1381
#define IDC_RADIO_RC_24M                             1382
#define IDC_RADIO_MII_MODE                           1383
#define IDC_RADIO_RMII_MODE                          1384
#define IDC_RADIO_SPIM_SEL0                          1385
#define IDC_RADIO_SPIM_SEL1                          1386
#define IDC_RADIO_SPIM_SEL2                          1387
#define IDC_RADIO_SPIM_SEL3                          1388
#define IDC_GROUP_FSYS                               1389
#define IDC_RADIO_FSYS_HIRC                          1390
#define IDC_RADIO_FSYS_LIRC                          1391
#define IDC_GROUP_RPD                                1392
#define IDC_RADIO_RPD_RESET                          1393
#define IDC_RADIO_RPD_INPUT                          1394
#define IDC_GROUP_OCDPWM                             1395
#define IDC_RADIO_OCDPWM_TRI                         1396
#define IDC_RADIO_OCDPWM_CONTI                       1397
#define IDC_GROUP_LDSIZE                             1398
#define IDC_RADIO_LDSIZE_0K                          1399
#define IDC_RADIO_LDSIZE_1K                          1400
#define IDC_RADIO_LDSIZE_2K                          1401
#define IDC_RADIO_LDSIZE_3K                          1402
#define IDC_RADIO_LDSIZE_4K                          1403
#define IDC_GROUP_WDT                                1404
#define IDC_RADIO_WDT_DISABLE                        1405
#define IDC_RADIO_WDT_ENABLE_STOP                    1406
#define IDC_RADIO_WDT_ENABLE_KEEP                    1407
#define IDC_CHECK_OCD_ENABLE                         1408
#define IDC_COMBO_GPA0_RINI                          1409
#define IDC_COMBO_GPA1_RINI                          1410
#define IDC_COMBO_GPA2_RINI                          1411
#define IDC_COMBO_GPA3_RINI                          1412
#define IDC_COMBO_GPA4_RINI                          1413
#define IDC_COMBO_GPA5_RINI                          1414
#define IDC_STATIC_GPA0                              1415
#define IDC_STATIC_GPA1                              1416
#define IDC_STATIC_GPA2                              1417
#define IDC_STATIC_GPA3                              1418
#define IDC_STATIC_GPA4                              1419
#define IDC_STATIC_GPA5                              1420
#define IDC_RADIO_UART1_SEL0                         1421
#define IDC_RADIO_UART1_SEL1                         1422
#define IDC_RADIO_UART1_SEL2                         1423
#define IDC_RADIO_UART1_SEL3                         1424
#define IDC_RADIO_UART1_SEL4                         1425
#define IDC_CHECK_CHZ_BPWM_Ctrl                      1426
#define IDC_CHECK_CHZ_Even0_Ctrl                     1427
#define IDC_CHECK_CHZ_Odd0_Ctrl                      1428
#define IDC_CHECK_CHZ_Even1_Ctrl                     1429
#define IDC_CHECK_CHZ_Odd1_Ctrl                      1430
#define IDC_RADIO_LVR_LEVEL_0                        1431
#define IDC_RADIO_LVR_LEVEL_1                        1432
#define IDC_RADIO_HXT_MODE_0                         1433
#define IDC_RADIO_HXT_MODE_1                         1434
#define IDC_RADIO_CHIPRESET_TIMEEXT_0                1435
#define IDC_RADIO_CHIPRESET_TIMEEXT_1                1436
#define IDC_RADIO_RST_PIN_WIDTH_0                    1437
#define IDC_RADIO_RST_PIN_WIDTH_1                    1438
#define IDC_CHECK_TAMPER_POWER_DOWN                  1439
#define IDC_RADIO_BOOT_CLOCK_SELECT_0                1440
#define IDC_RADIO_BOOT_CLOCK_SELECT_1                1441
#define IDC_GROUP_BOOT_CLOCK_SELECT                  1442
#define IDC_CHECK_MIRROR_BOUNDARY                    1443
#define IDC_GROUP_LOAD_FAIL_OPTION                   1444
#define IDC_GROUP_STRAP_SELECT                       1445
#define IDC_RADIO_LOAD_FAIL_DISABLE                  1446
#define IDC_RADIO_LOAD_FAIL_ENABLE                   1447
#define IDC_RADIO_STRAP_PIN                          1448
#define IDC_RADIO_STRAP_FUSE                         1449
#define IDC_CHECK_JTAG_BOOTFAIL                      1450
#define IDC_CHECK_CLEAR_RSTSTS                       1451
#define IDC_CHECK_JTAG_BOOTSUCCESS                   1452
#define IDC_CHECK_PIN_WAKEUP_0                       1453
#define IDC_CHECK_PIN_WAKEUP_1                       1454
#define IDC_CHECK_PIN_WAKEUP_2                       1455
#define IDC_CHECK_PIN_WAKEUP_3                       1456
#define IDC_COMBO_PIN_WAKEUP_0                       1457
#define IDC_COMBO_PIN_WAKEUP_1                       1458
#define IDC_COMBO_PIN_WAKEUP_2                       1459
#define IDC_COMBO_PIN_WAKEUP_3                       1460
#define IDC_COMBO_FUSE_RETRY                         1461
#define IDC_RADIO_RSTDEB_0                           1462
#define IDC_RADIO_RSTDEB_1                           1463
#define IDC_RADIO_RSTDEB_2                           1464
#define IDC_RADIO_RSTDEB_3                           1465
#define IDC_GROUP_RESET_DEB_SELECT                   1466
#define IDC_CHECK_DFMC_EEPROM                        1467
#define IDC_CHECK_DFMC_EEPROM_SEC                    1468
#define IDC_EDIT_DFMC_NSCBA                          1469
#define IDC_GROUP_DFMC_CONFIG                        1470
#define IDC_SPIN_DFMC_NSCBA                          1471
#define IDC_STATIC_DFMC_NSCBA                        1472
#define IDS_KM1M2_SERIES                             1473

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        159
#define _APS_NEXT_COMMAND_VALUE         32843
#define _APS_NEXT_CONTROL_VALUE         1464
#define _APS_NEXT_SYMED_VALUE           299
#endif
#endif
