//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ISPTool.rc
//
#define IDM_ABOUTBOX                                 0x0010
#define IDD_ABOUTBOX                                 100
#define IDD_DIALOG_CONFIGURATION_NUC100              101
#define IDD_DIALOG_HEX                               102
#define IDD_DIALOG_CONFIGURATION_M051                103
#define IDD_DIALOG_CONFIGURATION_M051BN              104
#define IDD_DIALOG_NUVOISP                           105
#define IDD_DIALOG_NUVOISP_WITH_SPI                  106
#define IDD_DIALOG_CONFIGURATION_NANO100             107
#define IDD_DIALOG_CONFIGURATION_MINI51              108
#define IDD_DIALOG_CONFIGURATION_NUC200              109
#define IDD_DIALOG_CONFIGURATION_NUC103              110
#define IDD_DIALOG_CONFIGURATION_M051CN              111
#define IDD_DIALOG_CONFIGURATION_MT500               112
#define IDD_DIALOG_CONFIGURATION_NANO100BN           113
#define IDD_DIALOG_CONFIGURATION_NUC102              114
#define IDD_DIALOG_CONFIGURATION_AU9100              115
#define IDD_DIALOG_CONFIGURATION_M058                116
#define IDD_DIALOG_CONFIGURATION_NUC400              117
#define IDD_DIALOG_CONFIGURATION_MINI51CN            118
#define IDD_DIALOG_CONFIGURATION_NUC103BN            119
#define IDD_DIALOG_CONFIGURATION_NANO112             120
#define IDD_DIALOG_CONFIGURATION_NUC131              121
#define IDD_DIALOG_CONFIGURATION_NM1200              122
#define IDD_DIALOG_CONFIGURATION_NANO103             123
#define IDD_DIALOG_CONFIGURATION_NM1120              124
#define IDD_DIALOG_CONFIGURATION_N570                125
#define IDD_DIALOG_CONFIGURATION_OT8051              126
#define IDD_DIALOG_CONFIGURATION_M0564               127
#define IDD_DIALOG_CHIP_SETTING_M2351                128
#define IDD_DIALOG_CHIP_SETTING_CFG_M2351            129
#define IDD_DIALOG_CONFIGURATION_I94000              130
#define IDD_DIALOG_CHIP_SETTING_M251                 131
#define IDD_DIALOG_CHIP_SETTING_CFG_M251             132
#define IDD_DIALOG_CONFIGURATION_M480LD              133
#define IDD_DIALOG_CONFIGURATION_M480                134
#define IDD_DIALOG_CONFIGURATION_I91200              135
#define IDD_DIALOG_CHIP_SETTING_CFG_M258             136
#define IDD_DIALOG_CHIP_SETTING_NUMICRO1             137
#define IDD_DIALOG_CHIP_SETTING_NUMICRO              138
#define IDD_DIALOG_CHIP_SETTING_CFG_M0A21            139
#define IDD_DIALOG_CONFIGURATION_NUC1262             140
#define IDD_DIALOG_CHIP_SETTING_CFG_M460             141
#define IDD_DIALOG_CHIP_SETTING_CFG_M2L31            142
#define IDD_DIALOG_CHIP_SETTING_CFG_M2L31_2          143


#define IDR_MAINFRAME                                1000
#define IDB_BITMAP_BANNER                            1001
#define IDB_BITMAP_NUVOTON                           1002
#define IDI_ICON_MEMORY                              1003
#define IDB_BITMAP_CHIPS                             1004
#define IDC_GROUP_INTERFACE                          1005
#define IDC_COMBO_INTERFACE                          1006
#define IDC_COMBO_COM_PORT                           1007
#define IDC_CHECK_RUN_APROM                          1008
#define IDC_LINK_GITHUB                              1009
#define IDC_LINK_GITEE                               1010
#define IDC_LINK_GITLAB                              1011
#define IDI_ICON_NULINK                              1012
#define IDI_ICON_KEY_INPUT                           1013
#define IDC_PROGRESS                                 1014
#define IDC_BUTTON_CONNECT                           1015
#define IDC_BUTTON_CONFIG                            1016
#define IDC_BUTTON_START                             1017
#define IDC_BUTTON_APROM                             1018
#define IDC_BUTTON_NVM                               1019
#define IDC_CHECK_LDROM                              1020
#define IDC_CHECK_APROM                              1021
#define IDC_CHECK_NVM                                1022
#define IDC_CHECK_CONFIG                             1023
#define IDC_GROUP_CONNECT                            1024
#define IDC_STATIC_CONNECT                           1025
#define IDC_STATIC_PARTNO                            1026
#define IDC_GROUP_FLASH_FILE                         1027
#define IDC_STATIC_FILENAME_0                        1028
#define IDC_STATIC_FILENAME_1                        1029
#define IDC_STATIC_FILEINFO_APROM                    1030
#define IDC_STATIC_FILEINFO_NVM                      1031
#define IDC_GROUP_DATA                               1032
#define IDC_GROUP_FILE_DATA                          1033
#define IDC_GROUP_PROGRAM                            1034
#define IDC_STATIC_STATUS                            1035
#define IDC_EDIT_FILEPATH_APROM                      1036
#define IDC_EDIT_FILEPATH_NVM                        1037
#define IDC_TAB_DATA                                 1038
#define IDC_CHECK_ERASE                              1039
#define IDC_CHECK_ERASE_SPI                          1040
#define IDC_EDIT_PARTNO                              1041
#define IDC_BUTTON_SAVE_AS                           1042
#define IDC_RADIO_UINT8                              1043
#define IDC_RADIO_UINT16                             1044
#define IDC_RADIO_UINT32                             1045
#define IDC_RICHEDIT_DATAVIEW                        1046
#define IDC_EDIT_DATAVIEW                            1047
#define IDC_LINK_NUVOTON                             1048
#define IDC_STATIC_MESSAGE                           1049
#define IDC_EDIT_APROM_BASE_ADDRESS                  1050
#define IDC_STATIC_APOFFSET                          1051
#define IDC_RADIO_HIRC_ENABLE                        1052
#define IDC_RADIO_HIRC                               1053
#define IDC_CHECK_LVOL_RSTEN                         1054
#define IDC_CHECK_BOD_HYS_EN                         1055
#define IDC_BUTTON_SPI                               1056
#define IDC_EDIT_FILEPATH_SPI                        1057
#define IDC_STATIC_FILEINFO_SPI                      1058
#define IDC_CHECK_SPI                                1059
#define IDC_TAB_CHIP_SETTING                         1060
#define IDC_CHECK_ADCINTEN                           1061
#define IDC_STATIC_FILENAME_SPI                      1062
#define IDC_EDIT_IPADDRESS                           1063
#define IDC_EDIT_IPPORT                              1064
#define IDC_CHECK_SECURITY_BOOT_LOCK                 1065
#define IDC_BUTTON_SELECT_ALL_0                      1066
#define IDC_BUTTON_CLEAR_ALL_0                       1067
#define IDC_STATIC_0                                 1068
#define IDC_BUTTON_SELECT_ALL_1                      1069
#define IDC_STATIC_1                                 1070
#define IDC_BUTTON_CLEAR_ALL_1                       1071
#define IDC_GROUP_LOCK_LEVEL                         1072
#define IDC_GROUP_LOCK_PIN                           1073
#define IDC_GROUP_IODEFAULT                          1074
#define IDC_GROUP_SYSCLKDIV                          1075
#define IDC_GROUP_ISP_MODE                           1076
#define IDC_RADIO_IODEFAULT_INPUT                    1077
#define IDC_RADIO_IODEFAULT_QUASI                    1078
#define IDC_RADIO_SYSCLKDIV_0                        1079
#define IDC_RADIO_SYSCLKDIV_1                        1080
#define IDC_RADIO_SYSCLKDIV_2                        1081
#define IDC_RADIO_SYSCLKDIV_3                        1082
#define IDC_CHECK_ISP_MODE_UART                      1083
#define IDC_CHECK_ISP_MODE_USB                       1084
#define IDC_CHECK_ISP_MODE_CAN                       1085
#define IDC_CHECK_ISP_MODE_I2C                       1086
#define IDC_CHECK_ISP_MODE_SPI                       1087
#define IDC_STATIC_FLASH_KEYSTORE_LOCK               1088
#define IDC_EDIT_FLASH_KEYSTORE_LOCK                 1089
#define IDC_EDIT_BDNAME                              1090


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE                     144
#define _APS_NEXT_COMMAND_VALUE                      32843
#define _APS_NEXT_CONTROL_VALUE                      1091
#define _APS_NEXT_SYMED_VALUE                        299
#endif
#endif
