//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ISPTool.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDC_BUTTON_GENERATE             102
#define IDR_MAINFRAME                   102
#define IDB_BITMAP_BANNER               103
#define IDB_BITMAP_NUVOTON              104
#define IDI_ICON_MEMORY                 106
#define IDD_DIALOG_CONFIGURATION_NUC100 107
#define IDD_DIALOG_HEX                  108
#define IDC_BUTTON_IMPORT               109
#define IDB_BITMAP_CHIPS                113
#define IDD_DIALOG_CONFIGURATION_M051   119
#define IDD_DIALOG_CONFIGURATION_M051BN 120
#define IDD_DIALOG_NUVOISP              121
#define IDC_GROUP_INTERFACE             122
#define IDC_COMBO_INTERFACE             123
#define IDC_COMBO_COM_PORT              124
#define IDC_CHECK_RUN_APROM             125
#define IDC_LINK_GITHUB                 126
#define IDC_LINK_GITEE                  127
#define IDC_LINK_GITLAB                 128
#define IDD_DIALOG_NUVOISP_WITH_SPI     129
#define IDD_DIALOG_CONFIGURATION_NANO100 130
#define IDD_DIALOG_CONFIGURATION_MINI51 132
#define IDI_ICON_NULINK                 134
#define IDD_DIALOG_CONFIGURATION_NUC200 136
#define IDD_DIALOG_CONFIGURATION_NUC103 137
#define IDD_DIALOG_CONFIGURATION_M051CN 140
#define IDD_DIALOG_CONFIGURATION_MT500  141
#define IDD_DIALOG_CONFIGURATION_NANO100BN 144
#define IDD_DIALOG_CONFIGURATION_NUC102 145
#define IDD_DIALOG_CONFIGURATION_AU9100 146
#define IDD_DIALOG_CONFIGURATION_NUC101 148
#define IDI_ICON_VERSION_MISMATCH       156
#define IDI_ICON_KEY_INPUT              158
#define IDC_FW_FILE                     1000
#define IDC_BUTTON_BROWSER              1001
#define IDC_COMBO_SELECT_AREA           1002
#define IDC_STATIC_FLASH_INFO           1003
#define IDC_BUTTON_DOWNLOAD             1004
#define IDC_STATIC_DEVICE_STATUS        1005
#define IDC_PROGRESS                    1006
#define IDC_BUTTON_CANCEL_DOWNLOAD      1007
#define IDC_BUTTON_CONNECT              1008
#define IDC_BUTTON_CONFIG               1009
#define IDC_BUTTON_START                1010
#define IDC_COMBO_CONFIG                1011
#define IDC_BUTTON_LDROM                1012
#define IDC_BUTTON_APROM                1013
#define IDC_BUTTON_NVM                  1014
#define IDC_CHECK_LDROM                 1016
#define IDC_CHECK_APROM                 1017
#define IDC_CHECK_NVM                   1018
#define IDC_CHECK_CONFIG                1019
#define IDC_GROUP_CONNECT               1020
#define IDC_STATIC_CONNECT              1021
#define IDC_GROUP_PARTNO                1022
#define IDC_BUTTON_EXT                  1022
#define IDC_STATIC_PARTNO               1023
#define IDC_GROUP_FLASH_FILE            1024
#define IDC_STATIC_FILENAME_0           1025
#define IDC_STATIC_FILENAME_1           1026
#define IDC_STATIC_FILEINFO_LDROM       1028
#define IDC_STATIC_FILEINFO_APROM       1029
#define IDC_STATIC_FILEINFO_NVM         1030
#define IDC_CHECK_EXT                   1036
#define IDC_GROUP_DATA                  1037
#define IDC_STATIC_FILEINFO_EXT         1037
#define IDC_GROUP_FILE_DATA             1038
#define IDC_GROUP_EXT                   1039
#define IDC_GROUP_PROGRAM               1040
#define IDC_LINK_PROGRAM_OPTION         1042
#define IDC_STATIC_STATUS               1043
#define IDC_EDIT_FILEPATH_LDROM         1044
#define IDC_LINK_SPI_OPTION             1045
#define IDC_EDIT_FILEPATH_APROM         1046
#define IDC_EDIT_FILEPATH_NVM           1047
#define IDC_EDIT_FILEPATH_EXT           1048
#define IDC_GROUP_FLASH_DATA            1052
#define IDC_GROUP_OFFLINE_FLASH_DATA    1053
#define IDC_TAB_DATA                    1056
#define IDC_BUTTON_DEFAULT              1057
#define IDC_STATIC_HEAD_IMAGE           1060
#define IDC_CHECK_ERASE                 1067
#define IDC_EDIT_FLASH_INFO2            1068
#define IDC_CHECK_LDROM_WR_PROTECT      1068
#define IDC_CHECK_ERASE_SPI             1068
#define IDC_CHECK_BLANKCHECK            1069
#define IDC_EDIT_FLASH_INFO3            1070
#define IDC_CHECK_PROGRAM               1071
#define IDC_EDIT_FLASH_INFO4            1072
#define IDC_CHECK_PROGRAM_CIPHER        1072
#define IDC_CHECK_VERIFY                1073
#define IDC_CHECK_VERIFY_SPI            1074
#define IDC_CHECK_OFFLINE_MODE          1075
#define IDC_CHECK_OFFLINE_MODE_PASSWORD 1077
#define IDC_LINK_NUVOTON_M0             1080
#define IDC_LINK_NUVOTON_M0_SC          1081
#define IDC_EDIT_PARTNO                 1089
#define IDC_BUTTON_SAVE_AS              1090
#define IDC_RADIO_UINT8                 1091
#define IDC_RADIO_UINT16                1092
#define IDC_RADIO_UINT32                1093
#define IDC_BUTTON_REFRESH              1094
#define IDC_RICHEDIT_DATAVIEW           1095
#define IDC_EDIT_DATAVIEW               1096
#define IDC_LINK_LUA                    1097
#define IDC_BUTTON_REFRESH_EXT          1097
#define IDC_LINK_ELF                    1098
#define IDC_LINK_ELF2                   1099
#define IDC_LINK_NUVOTON                1100
#define IDC_LINK_DOWNLOAD               1101
#define IDC_STATIC_MESSAGE              1102
#define IDC_COMBO_PART_NO               1103
#define IDC_COMBO_CHIPS                 1104
#define IDC_GROUP_CVDTV                 1107
#define IDC_RADIO_CVDTV_27              1108
#define IDC_RADIO_CVDTV_30              1109
#define IDC_CHECK_CVDEN                 1110
#define IDC_EDIT_FLASH_INFO1            1111
#define IDC_COMBO_LANGUAGE              1112
#define IDC_EDIT_PASSWORD0              1113
#define IDC_EDIT_PASSWORD1              1114
#define IDC_EDIT_PASSWORD               1115
#define IDC_STATIC_INFO                 1116
#define IDC_STATIC_TITLE                1117
#define IDC_BUTTON_SPI_FLASH            1118
#define IDC_EDIT_FILEPATH_SPI_FLASH     1119
#define IDC_STATIC_FILEINFO_SPI_FLASH   1120
#define IDC_CHECK_SPI_FLASH             1121
#define IDC_EDIT_CUSTOMER               1122
#define IDC_EDIT_CUSTOMER_CODE          1123
#define IDC_EDIT_PRIVATE_KEY            1124
#define IDC_BUTTON_OPEN                 1126
#define IDC_EDIT_FILEPATH_FRM_FILE      1127
#define IDC_STATIC_CHECKSUM             1129
#define IDC_STATIC_MAP0                 1130
#define IDC_STATIC_MAP2                 1131
#define IDC_NO_PROMPT                   1132
#define IDC_BUTTON_START_APROM          1133
#define IDC_BUTTON_START_LDROM          1134
#define IDC_BUTTON_START_NVM            1135
#define IDC_BUTTON_ALL                  1136
#define IDC_EDIT_FILEPATH_ALL           1137
#define IDC_BUTTON_START_ALL            1138
#define IDC_STATIC_FILEINFO_ALL         1139
#define IDC_RADIO_IO_VOLTAGE_0          1141
#define IDC_RADIO_IO_VOLTAGE_1          1142
#define IDC_RADIO_IO_VOLTAGE_2          1143
#define IDC_RADIO_IO_VOLTAGE_3          1144
#define IDC_STATIC_POWER_MSG            1145
#define IDC_CHECK_OUTPUT_POWER          1146
#define IDC_STATIC_POWER_CONTROL        1147
#define IDC_STATIC_IO_VOLTAGE           1148
#define IDC_EDIT_READADDR               1149
#define IDC_EDIT_READLEN                1150
#define IDC_STATIC_READADDR             1151
#define IDC_STATIC_READLEN              1152
#define IDC_TAB_PROGRAMSETTING          1153
#define IDC_EDIT_FILEOFFSET             1155
#define IDC_EDIT_SN_START               1156
#define IDC_EDIT_EXTSTORAGEWOFFSET      1156
#define IDC_EDIT_SN_ADDRESS             1157
#define IDC_EDIT_EXTSTORAGEWLEN         1157
#define IDC_CHECK_SERIAL_NUMBER         1158
#define IDC_STATIC_FILESIZE             1158
#define IDC_CHECK_OFFLINE_LIMIT_COUNT   1159
#define IDC_STATIC_EXTSTORAGESIZE       1159
#define IDC_EDIT_MAX_OFFLINE_COUNT      1160
#define IDC_STATIC_FILEOFFSET           1160
#define IDC_STATIC_GROUP_SERIAL_NUMBER  1161
#define IDC_STATIC_EXTSTORAGEWOFFSET    1161
#define IDC_STATIC_SN_START             1162
#define IDC_STATIC_EXTSTORAGEWLEN       1162
#define IDC_STATIC_SN_ADDRESS           1163
#define IDC_STATIC_FILESIZED            1163
#define IDC_STATIC_SN_START1            1164
#define IDC_STATIC_EXTSTORAGED          1164
#define IDC_STATIC_SN_ADDRESS_1         1165
#define IDC_STATIC_GROUP_OFFLINE        1166
#define IDC_STATIC_PASSWORD0            1167
#define IDC_STATIC_PASSWORD1            1168
#define IDC_STATIC_MAX_COUNT            1169
#define IDC_CHECK_RESET                 1170
#define IDC_CHECK_AUTO_DETECT           1172
#define IDC_LINK_TEST_USE               1173
#define IDC_RADIO0                      1174
#define IDC_RADIO2                      1175
#define IDC_RADIO1                      1176
#define IDC_RADIO3                      1177
#define IDC_STATIC_GROUP                1178
#define IDC_RADIO10                     1178
#define IDC_RADIO_PWM_EVEN_0            1179
#define IDC_RADIO4                      1179
#define IDC_RADIO_PWM_EVEN_1            1180
#define IDC_RADIO5                      1180
#define IDC_RADIO_PWM_ODD_0             1181
#define IDC_RADIO6                      1181
#define IDC_RADIO_PWM_ODD_1             1182
#define IDC_RADIO7                      1182
#define IDC_RADIO8                      1183
#define IDC_CHECK_LVR2V_ENABLE          1184
#define IDC_RADIO9                      1184
#define IDC_EDIT_CERT_FILE              1185
#define IDC_BUTTON_CERT_FILE            1186
#define IDC_CHECK_ONLINE_LIMIT_COUNT    1187
#define IDC_STATIC_CERT_FILE            1188
#define IDC_STATIC_HELP                 1189
#define IDC_EDIT_MAX_ONLINE_COUNT       1190
#define IDC_STATIC_MAX_NUMBER           1195
#define IDC_COMBO_SPIFLASH_LIST         1195
#define IDC_STATIC_EXTSTORAGETYPE       1206
#define IDC_STATIC_EXTSTORAGE_LENGTH    1207
#define IDC_STATIC_EXTSTORAGE_CHECKSUM  1208
#define IDC_EDIT_EXT_ADDR               1209
#define IDC_STATIC_SPIFLASH_INFO        1209
#define IDC_BUTTON_VERSION_MATCH        1209
#define IDC_STATIC_EXT_ADDR             1210
#define IDC_STATIC_EXTSTORAGE_LENGTH_LABEL 1210
#define IDC_BUTTON_APROM_KEYINPUT       1210
#define IDC_EDIT_EXT_SIZE               1211
#define IDC_STATIC_SPI_BASE_ADDR        1211
#define IDC_STATIC_EXTSTORAGE_CHECKSUM_LABEL 1211
#define IDC_EDIT_RC4_KEYLIST            1211
#define IDC_STATIC_EXT_SIZE             1212
#define IDC_EDIT_APROM_BASE_ADDRESS     1212
#define IDC_EDIT_SPIFLASH_INFORMATION   1212
#define IDC_STATIC_SPI_DATA_RW_SIZE     1213
#define IDC_EDIT_SPI_DATA_RW_SIZE       1214
#define IDC_STATIC_SPI_DATA_RW_SIZE1    1215
#define IDC_STATIC_SPI_CODE_RW_SIZE     1216
#define IDC_EDIT_SPI_CODE_RW_SIZE       1217
#define IDC_STATIC_SPI_CODE_RW_SIZE1    1218
#define IDC_CHECK_PROGRAMFROM           1219
#define IDC_CHECK_BATCHMODE             1221
#define IDC_CHECK_SECURITYLOCK          1226
#define IDC_CHECK_RETAIN_SETTING_AFTER_FILECHANGE 1229
#define IDC_STATIC_WARNING              1253
#define IDC_GROUP_EXT_MODE              1254
#define IDC_RADIO_SPIM_MCP              1255
#define IDC_RADIO_SPIM_GPIO             1256
#define IDC_RADIO_EXT_LITTLEENDIAN      1258
#define IDC_RADIO_EXT_BIGENDIAN         1259
#define IDC_EDIT_LAST_BYTE              1267
#define IDC_STATIC_LAST_BYTE            1268
#define IDC_EDIT_APOFFSET               1269
#define IDC_STATIC_APOFFSET             1270
#define IDC_LINK_KEY_OPTION             1271
#define IDC_STATIC_SPIOFFSET            1272
#define IDC_EDIT_KEY0ROM_VALUE          1273
#define IDC_EDIT_KEY1ROM_VALUE          1274
#define IDC_EDIT_KEY2ROM_VALUE          1275
#define IDC_EDIT_KPMAXROM_VALUE         1276
#define IDC_EDIT_KEMAXROM_VALUE         1277
#define IDC_EDIT_KEY0ROM_VALUE2         1278
#define IDC_EDIT_KEY1ROM_VALUE2         1279
#define IDC_EDIT_KEY2ROM_VALUE2         1280
#define IDC_EDIT_LAST_BYTE_2            1283
#define IDC_EDIT_LAST_BYTE_3            1284
#define IDC_RADIO_HIRC_ENABLE           1284
#define IDC_RADIO_HIRC                  1285
#define IDC_CHECK_LVOL_RSTEN            1310
#define IDC_CHECK_BOD_HYS_EN            1311
#define IDC_EDIT_SECURE_KEY             1312
#define IDC_CHECK_CHECKSUM_VERIFY       1313
#define IDC_RADIO_HXT_H8                1314
#define IDC_RADIO_HXT_4                 1315
#define IDC_RADIO_HXT_H32               1318
#define IDC_RADIO_HXT_H24               1319
#define IDC_RADIO_HXT_H12               1320
#define IDC_BUTTON_EXPORT               1321
#define IDC_EDIT_FILEPATH_SECURE_KEY    1351
#define IDC_STATIC_FILEPATH_SECURE_KEY  1352
#define IDC_BUTTON_SPI                  1355
#define IDC_EDIT_FILEPATH_SPI           1356
#define IDC_STATIC_FILEINFO_SPI         1357
#define IDC_CHECK_SECURE_KEY            1358
#define IDC_BUTTON_SECURE_KEY           1359
#define IDC_CHECK_SPI                   1360
#define IDC_RADIO_PAGE0_SEL             1362
#define IDC_RADIO_PAGE1_SEL             1363
#define IDC_STATIC_SPIKEY_0             1366
#define IDC_STATIC_SPIKEY_1             1367
#define IDC_EDIT_SPIKEY0                1368
#define IDC_EDIT_SPIKEY1                1369
#define IDC_CHECK_SHOW_PASSWORD         1382
#define IDC_COMBO_VENDOR                1383
#define IDC_COMBO_SPIM_CLOCK            1384
#define IDC_EDIT_RESET0                 1385
#define IDC_EDIT_RESET1                 1386
#define IDC_EDIT_ENTER4BYTE             1387
#define IDC_EDIT_EXIT4BYTE              1388
#define IDC_EDIT_ENTER4BYTE_STATUS      1389
#define IDC_EDIT_SPIMCLOCK              1390
#define IDC_EDIT_RXDELAY                1391
#define IDC_EDIT_RXEDGE                 1392
#define IDC_EDIT_DUMMYCYCLE             1393
#define IDC_CHECK_IS32MB                1394
#define IDC_EDIT_RESERVE0               1395
#define IDC_EDIT_RESERVE1               1396
#define IDC_EDIT_RESERVE2               1397
#define IDC_EDIT_RESERVE3               1398
#define IDC_EDIT_RESERVE4               1399
#define IDC_EDIT_RESERVE5               1400
#define IDC_TAB_CHIP_SETTING            1401
#define IDC_STATIC_FILENAME_SPI         1478
#define IDC_CHECK_SECURITY_BOOT_LOCK    1485
#define IDD_DIALOG_CONFIGURATION_M058   5082
#define IDD_DIALOG_CONFIGURATION_NUC400 5084
#define IDD_DIALOG_CONFIGURATION_MINI51CN 5085
#define IDD_DIALOG_CONFIGURATION_NUC103BN 5086
#define IDD_DIALOG_CONFIGURATION_NANO112 5088
#define IDD_DIALOG_CONFIGURATION_NUC131 5091
#define IDD_DIALOG_CONFIGURATION_NM1200 5094
#define IDD_DIALOG_CONFIGURATION_NANO103 5099
#define IDD_DIALOG_CONFIGURATION_NM1120 5100
#define IDD_DIALOG_CONFIGURATION_N570   5101
#define IDD_DIALOG_CONFIGURATION_OT8051 5103
#define IDD_DIALOG_CONFIGURATION_M0564  5104
#define IDD_DIALOG_CONFIGURATION_TC8826 5107
#define IDD_DIALOG_CHIP_SETTING_M2351   5109
#define IDD_DIALOG_CONFIGURATION_M2351  5110
#define IDD_DIALOG_CONFIGURATION_I94000 5114
#define IDD_DIALOG_CHIP_SETTING_M251    5116
#define IDD_DIALOG_CHIP_SETTING_CFG_M251 5117
#define IDD_DIALOG_CONFIGURATION_M480LD 5127
#define IDD_DIALOG_CONFIGURATION_M480   5136
#define IDD_DIALOG_CONFIGURATION_I91200 5147
#define IDD_DIALOG_CHIP_SETTING_CFG_M258 5148
#define IDD_DIALOG_CHIP_SETTING_NUMICRO 5150
#define IDD_DIALOG_CHIP_SETTING_CFG_M0A21 5151
#define IDC_STATIC_MYMESSAGE            5535
#define IDC_STATIC_TOGET                5536
#define IDC_BUTTON_OK                   5537
#define IDC_BUTTON_NO                   5538
#define IDC_CHECK_NOPROMPT              5539
#define IDC_DYNAMIC_LINK1               6000
#define IDC_DYNAMIC_LINK2               6001
#define IDC_DYNAMIC_LINK3               6002
#define IDC_DYNAMIC_LINK4               6003
#define IDC_DYNAMIC_LINK5               6004
#define IDC_DYNAMIC_TITLE               6100
#define ID_SPIFLASH_SPI0                32809
#define ID_SPIFLASH_SPI1                32810
#define ID_SPIFLASH_SPI2                32811
#define ID_SPIFLASH_SPI3                32812
#define ID_SPIFLASH_BOOTSPI             32813
#define ID_DEVICE_READSPIFLASH          32815
#define ID_OPTION_PROGRAMCONFIGURATION  32817

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        567
#define _APS_NEXT_COMMAND_VALUE         32843
#define _APS_NEXT_CONTROL_VALUE         1479
#define _APS_NEXT_SYMED_VALUE           299
#endif
#endif
